USE master;
GO

CREATE LOGIN turismo_admin
WITH PASSWORD = 'CAMBIAR_PASSWORD';

CREATE LOGIN turismo_vendedor
WITH PASSWORD = 'CAMBIAR_PASSWORD';

CREATE LOGIN turismo_analista
WITH PASSWORD = 'CAMBIAR_PASSWORD';